export const FPS = 60;
export const MAP_WIDTH = 3000;
export const MAP_HEIGHT = 3000;

export const UPGRADES = [
    { id: 'DMG', name: 'Overclocked Core', desc: 'Damage +20%', rarity: 'common', apply: (p) => p.damage *= 1.2 },
    { id: 'SPD', name: 'Mag-Lev Servos', desc: 'Move Speed +15%', rarity: 'common', apply: (p) => p.speed *= 1.15 },
    { id: 'HP',  name: 'Titanium Plating', desc: 'Max HP +50', rarity: 'common', apply: (p) => { p.maxHp += 50; p.hp += 50; } },
    { id: 'SIZE', name: 'Heavy Caliber', desc: 'Bullet Size +50%', rarity: 'common', apply: (p) => p.bulletSize *= 1.5 },
    { id: 'THORN', name: 'Reactive Armor', desc: 'Contact deals 50 dmg', rarity: 'common', apply: (p) => p.thorns = true },
    { id: 'RATE', name: 'Rapid Cycler', desc: 'Fire Rate +15%', rarity: 'rare', apply: (p) => p.fireRate = Math.max(2, p.fireRate * 0.85) },
    { id: 'VAMP', name: 'Nanobot Siphon', desc: 'Heal 2HP on kill', rarity: 'rare', apply: (p) => p.lifesteal += 2 },
    { id: 'REGEN', name: 'Auto-Repair', desc: 'Regen 1HP/sec', rarity: 'rare', apply: (p) => p.regen += 1 },
    { id: 'EXEC', name: 'Executioner', desc: 'Dmg x2 vs targets <30% HP', rarity: 'rare', apply: (p) => p.execute = true },
    { id: 'FROST', name: 'Cryo Rounds', desc: 'Bullets slow enemies', rarity: 'rare', apply: (p) => p.frost = true },
    { id: 'MULTI', name: 'Splitter Matrix', desc: '+1 Projectile', rarity: 'legendary', apply: (p) => p.bulletCount += 1 },
    { id: 'RICO', name: 'Bounce Plating', desc: 'Bullets bounce once', rarity: 'legendary', apply: (p) => p.ricochet = true },
    { id: 'GLASS', name: 'Glass Cannon', desc: 'Dmg x2, Max HP / 2', rarity: 'legendary', apply: (p) => { p.damage *= 2; p.maxHp = Math.floor(p.maxHp/2); p.hp = Math.min(p.hp, p.maxHp); } },
    { id: 'GAMBLE', name: 'Chaos Engine', desc: 'Dmg varies (0.5x - 3.0x)', rarity: 'legendary', apply: (p) => p.gambler = true },
    { id: 'HOMING', name: 'Smart Targeting', desc: 'Bullets steer to targets', rarity: 'legendary', apply: (p) => p.homing = true },
    { id: 'PIERCE', name: 'Railgun Module', desc: 'Bullets pierce 1 target', rarity: 'rare', apply: (p) => p.pierce = (p.pierce || 0) + 1 },
    { id: 'CLUSTER', name: 'Cluster Munitions', desc: 'Explode on impact', rarity: 'legendary', apply: (p) => p.cluster = true },
    { id: 'ADRENALINE', name: 'Berserk OS', desc: 'Low HP = High Fire Rate', rarity: 'rare', apply: (p) => p.adrenaline = true },
    { id: 'DODGE', name: 'Phase Shift', desc: '15% chance to dodge dmg', rarity: 'rare', apply: (p) => p.dodgeChance = (p.dodgeChance || 0) + 0.15 },
    { id: 'TOXIC', name: 'Venomous Rounds', desc: 'Bullets apply acid', rarity: 'rare', apply: (p) => p.acid = true },
    { id: 'CRIT', name: 'Targeting Computer', desc: '15% Chance for 2x Dmg', rarity: 'rare', apply: (p) => p.critChance = (p.critChance || 0) + 0.15 },
    { id: 'ARMOR', name: 'Plasteel Plating', desc: '-15% Damage Taken', rarity: 'rare', apply: (p) => p.damageReduction = (p.damageReduction || 0) + 0.15 },
    { id: 'KNOCK', name: 'Concussive Shells', desc: 'Increased Knockback', rarity: 'common', apply: (p) => p.knockback = (p.knockback || 0) + 10 },
    { id: 'TINY', name: 'Compact Frame', desc: 'Size -30%, Speed +10%', rarity: 'legendary', apply: (p) => { p.size *= 0.7; p.speed *= 1.1; } },
    { id: 'BOSS', name: 'Giant Slayer', desc: '+50% Dmg vs Bosses', rarity: 'rare', apply: (p) => p.bossKiller = true },
    { id: 'AURA', name: 'Static Field', desc: 'Zaps nearby enemies', rarity: 'legendary', apply: (p) => p.staticAura = true },
    { id: 'BLOOD', name: 'Blood Pact', desc: 'Dmg +40%, Max HP -20%', rarity: 'legendary', apply: (p) => { p.damage *= 1.4; p.maxHp *= 0.8; p.hp = Math.min(p.hp, p.maxHp); } },
    { id: 'HEAVY', name: 'Depleted Uranium', desc: 'Dmg +30%, Bullet Speed -15%', rarity: 'rare', apply: (p) => { p.damage *= 1.3; p.bulletSpeed *= 0.85; } },
    { id: 'SNIPER_MOD', name: 'Long Barrel', desc: 'Range +50%, Speed +20%', rarity: 'common', apply: (p) => { p.bulletLife = (p.bulletLife || 60) * 1.5; p.bulletSpeed *= 1.2; } },
    { id: 'CDR', name: 'Heat Sink', desc: 'Ability Cooldown -15%', rarity: 'rare', apply: (p) => p.abilityCd *= 0.85 },
    { id: 'XP', name: 'Neural Link', desc: 'XP Gain +20%', rarity: 'common', apply: (p) => p.xpMult = (p.xpMult || 1) + 0.2 },
    { id: 'CQB', name: 'Brawler Module', desc: '+25% Dmg within 400px', rarity: 'common', apply: (p) => p.closeDmg = true },
    { id: 'SNIPER_LENS', name: 'Sniper Lens', desc: '+25% Dmg beyond 700px', rarity: 'common', apply: (p) => p.farDmg = true },
    { id: 'TESLA', name: 'Tesla Coil', desc: '20% Chance to Arc Lightning', rarity: 'legendary', apply: (p) => p.tesla = true },
    { id: 'RAM', name: 'Impact Bumper', desc: 'Dash deals 150 Dmg', rarity: 'rare', apply: (p) => p.ramDmg = true },
    { id: 'TURRET', name: 'Shoulder Cannon', desc: 'Fires auto-shots', rarity: 'rare', apply: (p) => p.turret = true },
    { id: 'CHARGE', name: 'Capacitor', desc: 'Every 5th shot deals 2x Dmg', rarity: 'common', apply: (p) => p.chargedShot = true },
    { id: 'LUCK', name: 'Lucky Charm', desc: '+5% Dodge/Crit/Gamble', rarity: 'rare', apply: (p) => { p.dodgeChance = (p.dodgeChance||0)+0.05; p.critChance = (p.critChance||0)+0.05; } },
    { id: 'ORBITAL', name: 'Defensive Drone', desc: 'Orbiting drone blocks shots/dmg', rarity: 'rare', apply: (p) => p.orbital = true },
    { id: 'STATIONARY', name: 'Siege Mode', desc: '+50% Dmg when standing still', rarity: 'rare', apply: (p) => p.stationary = true },
    { id: 'RUN_N_GUN', name: 'Run N Gun', desc: '+30% Fire Rate when moving', rarity: 'rare', apply: (p) => p.runngun = true },
    { id: 'CORPSE', name: 'Volatile Enemies', desc: 'Enemies explode on death', rarity: 'rare', apply: (p) => p.corpseExplosion = true },
    { id: 'GROWING', name: 'Expanding Shot', desc: 'Bullets grow larger over distance', rarity: 'rare', apply: (p) => p.growingShot = true },
    { id: 'WITHER', name: 'Wither', desc: 'Enemies hit deal -20% Dmg', rarity: 'rare', apply: (p) => p.wither = true },
    { id: 'CONFUSE', name: 'Scramble', desc: '10% Chance to confuse enemies', rarity: 'rare', apply: (p) => p.confuse = true },
    { id: 'PHOENIX', name: 'Phoenix Protocol', desc: 'Prevent death once (Heal 50%)', rarity: 'legendary', apply: (p) => p.phoenix = true },
    { id: 'FOCUS', name: 'Hyper Focus', desc: 'Spread reduces as you fire', rarity: 'rare', apply: (p) => p.focus = true },
    { id: 'MAGNET', name: 'Gravity Well', desc: 'Slows enemy bullets near you', rarity: 'rare', apply: (p) => p.magnetic = true }
];

export const ENEMY_TYPES = {
    SWARMER: { hp: 10, speed: 8, score: 5, color: '#ff6666', size: 12, ai: 'RUSH' },
    DRONE: { hp: 30, speed: 3, score: 10, color: '#ff3333', size: 20, ai: 'CHASE' },
    KAMIKAZE: { hp: 20, speed: 6, score: 20, color: '#ffaa00', size: 18, ai: 'RUSH' },
    TANK: { hp: 150, speed: 1.5, score: 50, color: '#880000', size: 35, ai: 'CHASE' },
    GUNNER: { hp: 40, speed: 2, score: 30, color: '#aa00ff', size: 22, ai: 'KITE' },
    ORBITER: { hp: 60, speed: 4, score: 40, color: '#0088ff', size: 25, ai: 'ORBIT' },
    STALKER: { hp: 80, speed: 2, score: 60, color: '#444444', size: 20, ai: 'TELEPORT' },
    ARTILLERY: { hp: 100, speed: 1, score: 70, color: '#dd5500', size: 30, ai: 'MORTAR' },
    SPLITTER: { hp: 60, speed: 4, score: 35, color: '#993399', size: 24, ai: 'CHASE' },
    MITE: { hp: 15, speed: 7, score: 10, color: '#aa66aa', size: 10, ai: 'RUSH' },
    MENDER: { hp: 80, speed: 3, score: 60, color: '#00ff88', size: 22, ai: 'HEALER' },
    RAILGUNNER: { hp: 70, speed: 2.5, score: 80, color: '#ff0055', size: 20, ai: 'SNIPER' },
    HUNTER: { hp: 90, speed: 6, score: 90, color: '#222222', size: 22, ai: 'STEALTH' },
    NOVA: { hp: 50, speed: 5, score: 45, color: '#ff9900', size: 22, ai: 'RUSH' }
};

export const BOSS_TYPES = [
    { name: 'HYDRA', hp: 4000, color: '#ff0000', size: 90, behavior: 'SPIN_SHOOT' },
    { name: 'PHANTOM', hp: 3500, color: '#444444', size: 80, behavior: 'TELEPORT_ASSAULT' },
    { name: 'BEHEMOTH', hp: 5000, color: '#550000', size: 110, behavior: 'SUMMON' },
    { name: 'INFERNO', hp: 5500, color: '#ff4500', size: 90, behavior: 'FIRE_TRAIL' },
    { name: 'VOID MAW', hp: 5000, color: '#220022', size: 100, behavior: 'SUCK' },
    { name: 'QUEEN', hp: 6000, color: '#880088', size: 100, behavior: 'ELITE_SUMMON' },
    { name: 'OMEGA', hp: 8000, color: '#ffffff', size: 120, behavior: 'ALL' },
    { name: 'STORM BRINGER', hp: 7500, color: '#00ffff', size: 95, behavior: 'LIGHTNING_STORM' },
    { name: 'IRON COLOSSUS', hp: 12000, color: '#555555', size: 150, behavior: 'LASER' },
    { name: 'DOOMSDAY', hp: 15000, color: '#000000', size: 160, behavior: 'NUKE' }
];

export const MECH_CLASSES = {
    SCOUT: { hp: 100, speed: 7, size: 20, color: '#00ffcc', fireRate: 15, damage: 10, bulletSpeed: 18, spread: 0.3, bulletCount: 3, ability: 'BLINK', abilityCd: 180, abilityName: "WARP JUMP" },
    HEAVY: { hp: 350, speed: 3, size: 30, color: '#ffaa00', fireRate: 40, damage: 60, bulletSpeed: 12, spread: 0.0, bulletCount: 1, ability: 'FORTRESS', abilityCd: 900, abilityName: "FORTRESS MODE", rocket: true },
    SNIPER: { hp: 80, speed: 5, size: 22, color: '#ff00ff', fireRate: 80, damage: 100, bulletSpeed: 40, spread: 0, bulletCount: 1, ability: 'HEADSHOT', abilityCd: 600, abilityName: "CALIBRATE", pierce: 10 },
    ASSAULT: { hp: 180, speed: 5, size: 25, color: '#33ff33', fireRate: 8, damage: 14, bulletSpeed: 20, spread: 0.15, bulletCount: 1, ability: 'BARRAGE', abilityCd: 180, abilityName: "MISSILE SWARM", bulletLife: 50 },
    ENGINEER: { hp: 140, speed: 4.5, size: 24, color: '#3388ff', fireRate: 10, damage: 8, bulletSpeed: 18, spread: 0.1, bulletCount: 1, ability: 'TURRET', abilityCd: 900, abilityName: "SENTRY GUN", tesla: true },
    PYRO: { hp: 200, speed: 5.5, size: 26, color: '#ff4500', fireRate: 3, damage: 6, bulletSpeed: 12, spread: 0.4, bulletCount: 2, ability: 'INFERNO', abilityCd: 240, abilityName: "OVERHEAT", bulletLife: 25 },
    LANCER: { hp: 160, speed: 6, size: 22, color: '#ccccff', fireRate: 40, damage: 60, bulletSpeed: 25, spread: 0, bulletCount: 1, ability: 'DASH', abilityCd: 120, abilityName: "VOID STRIKE", bulletLife: 30 },
    GHOST: { hp: 90, speed: 7, size: 18, color: '#dddddd', fireRate: 20, damage: 20, bulletSpeed: 18, spread: 0.0, bulletCount: 1, ability: 'HARVEST', abilityCd: 480, abilityName: "SOUL REAP", boomerang: true },
    TITAN: { hp: 400, speed: 2.5, size: 40, color: '#552200', fireRate: 10, damage: 8, bulletSpeed: 10, spread: 0.2, bulletCount: 4, ability: 'SLAM', abilityCd: 240, abilityName: "EARTH SHATTER" },
    SUMMONER: { hp: 120, speed: 5, size: 22, color: '#aaff00', fireRate: 25, damage: 10, bulletSpeed: 15, spread: 0.1, bulletCount: 1, ability: 'SENTRY', abilityCd: 400, abilityName: "DEPLOY DRONES" },
    BERSERKER: { hp: 250, speed: 6, size: 28, color: '#880000', fireRate: 20, damage: 40, bulletSpeed: 15, spread: 0.4, bulletCount: 1, ability: 'RAGE', abilityCd: 600, abilityName: "BLOOD FURY", bulletLife: 15 },
    CHRONOS: { hp: 110, speed: 5.5, size: 22, color: '#000088', fireRate: 12, damage: 12, bulletSpeed: 20, spread: 0.1, bulletCount: 1, ability: 'TIMESTOP', abilityCd: 900, abilityName: "ZA WARUDO" },
    ALCHEMIST: { hp: 140, speed: 5, size: 23, color: '#cc00ff', fireRate: 12, damage: 12, bulletSpeed: 16, spread: 0.2, bulletCount: 1, ability: 'STIM', abilityCd: 480, abilityName: "STIM PACK", acid: true },
    WARDEN: { hp: 220, speed: 4, size: 28, color: '#00ff88', fireRate: 4, damage: 25, bulletSpeed: 18, spread: 0.05, bulletCount: 1, ability: 'SANCTUARY', abilityCd: 900, abilityName: "SANCTUARY", ricochet: true, pierce: 2 },
    BARD: { hp: 100, speed: 6, size: 20, color: '#ff66cc', fireRate: 10, damage: 8, bulletSpeed: 15, spread: 0.3, bulletCount: 3, ability: 'ANTHEM', abilityCd: 360, abilityName: "POWER CHORD", pierce: 5, bulletLife: 30 },
    SHADE: { hp: 100, speed: 6.5, size: 20, color: '#4b0082', fireRate: 15, damage: 15, bulletSpeed: 20, spread: 0.1, bulletCount: 1, ability: 'FEAR', abilityCd: 420, abilityName: "NIGHTMARE" },
    JUGGERNAUT: { hp: 400, speed: 2, size: 40, color: '#8b4513', fireRate: 6, damage: 30, bulletSpeed: 12, spread: 0.2, bulletCount: 2, ability: 'UNSTOPPABLE', abilityCd: 600, abilityName: "UNSTOPPABLE" },
    ARCANIST: { hp: 110, speed: 5.5, size: 22, color: '#00bfff', fireRate: 18, damage: 12, bulletSpeed: 14, spread: 0.1, bulletCount: 3, ability: 'BLACKHOLE', abilityCd: 720, abilityName: "SINGULARITY", homing: true },
    GAMBLER: { hp: 150, speed: 5, size: 24, color: '#ffd700', fireRate: 10, damage: 15, bulletSpeed: 18, spread: 0.5, bulletCount: 1, ability: 'JACKPOT', abilityCd: 300, abilityName: "ROLL THE DICE", gambler: true },
    TRAPPER: { hp: 130, speed: 5, size: 22, color: '#2e8b57', fireRate: 20, damage: 10, bulletSpeed: 22, spread: 0.05, bulletCount: 1, ability: 'MINEFIELD', abilityCd: 300, abilityName: "MINEFIELD" },
    NINJA: { hp: 90, speed: 7.5, size: 18, color: '#222222', fireRate: 10, damage: 15, bulletSpeed: 25, spread: 0.3, bulletCount: 3, ability: 'DECOY', abilityCd: 480, abilityName: "SMOKE BOMB", pierce: 2 },
    DRUID: { hp: 160, speed: 4.5, size: 24, color: '#228b22', fireRate: 8, damage: 20, bulletSpeed: 16, spread: 0.1, bulletCount: 1, ability: 'ENTANGLE', abilityCd: 600, abilityName: "ROOTS", thorns: true },
    VOLT: { hp: 110, speed: 6, size: 20, color: '#ffd700', fireRate: 25, damage: 6, bulletSpeed: 28, spread: 0.15, bulletCount: 1, ability: 'OVERLOAD', abilityCd: 360, abilityName: "THUNDERSTRUCK", tesla: true },
    COMMANDER: { hp: 200, speed: 4, size: 26, color: '#4682b4', fireRate: 6, damage: 35, bulletSpeed: 20, spread: 0.05, bulletCount: 1, ability: 'AIRSTRIKE', abilityCd: 900, abilityName: "AIRSTRIKE" },
    HUNTRESS: { hp: 120, speed: 6.5, size: 20, color: '#8b0000', fireRate: 12, damage: 40, bulletSpeed: 24, spread: 0.05, bulletCount: 1, ability: 'MARK', abilityCd: 300, abilityName: "HUNTER'S MARK" },
    NECROMANCER: { hp: 100, speed: 5, size: 22, color: '#222222', fireRate: 15, damage: 12, bulletSpeed: 18, spread: 0.2, bulletCount: 1, ability: 'RAISE', abilityCd: 600, abilityName: "ARISE", necromancy: true },
    BEAMER: { hp: 110, speed: 6, size: 20, color: '#00ffff', fireRate: 4, damage: 4, bulletSpeed: 30, spread: 0, bulletCount: 1, ability: 'PRISM', abilityCd: 480, abilityName: "PRISM CORE", pierce: 5 },
    GUNSLINGER: { hp: 120, speed: 6, size: 22, color: '#8B4513', fireRate: 12, damage: 25, bulletSpeed: 25, spread: 0.05, bulletCount: 1, ability: 'DEADEYE', abilityCd: 600, abilityName: "DEAD EYE" },
    SHAMAN: { hp: 140, speed: 5, size: 24, color: '#006400', fireRate: 20, damage: 15, bulletSpeed: 15, spread: 0.1, bulletCount: 2, ability: 'TOTEM', abilityCd: 500, abilityName: "SUMMON TOTEM" },
    PLAGUE: { hp: 130, speed: 5.5, size: 23, color: '#808000', fireRate: 10, damage: 8, bulletSpeed: 16, spread: 0.3, bulletCount: 1, ability: 'OUTBREAK', abilityCd: 400, abilityName: "PANDEMIC", acid: true, plague: true },
    RONIN: { hp: 110, speed: 7.5, size: 18, color: '#DC143C', fireRate: 30, damage: 50, bulletSpeed: 20, spread: 0.1, bulletCount: 1, ability: 'OMNISLASH', abilityCd: 480, abilityName: "OMNISLASH", pierce: 10, bulletLife: 10 },
    HIVE: { hp: 120, speed: 5, size: 20, color: '#DAA520', fireRate: 20, damage: 5, bulletSpeed: 15, spread: 0.4, bulletCount: 2, ability: 'SWARM', abilityCd: 600, abilityName: "SWARM", homing: true },
    GRAVITY: { hp: 140, speed: 4, size: 26, color: '#4B0082', fireRate: 10, damage: 15, bulletSpeed: 10, spread: 0.1, bulletCount: 1, ability: 'REPULSE', abilityCd: 360, abilityName: "REPULSE", knockback: 50 },
    MARINE: { hp: 160, speed: 5.5, size: 22, color: '#556B2F', fireRate: 10, damage: 18, bulletSpeed: 22, spread: 0.05, bulletCount: 1, ability: 'GRENADE', abilityCd: 300, abilityName: "NUKE GRENADE" },
    PIRATE: { hp: 150, speed: 5, size: 24, color: '#800000', fireRate: 5, damage: 40, bulletSpeed: 15, spread: 0.1, bulletCount: 1, ability: 'CANNONBALL', abilityCd: 400, abilityName: "CANNONBALL", ricochet: true, bulletSize: 10 }
};

